Repository OpenVoxProject/openfact, pull requests merged in 2025-06, with the labels that each got.

#14 Fix rubocop offense
  lib/facter/custom_facts/core/suitable.rb
Labels: skip-changelog

#21 CI: Fix weird unicode in acceptance tests pipeline & disable MacOS 14/15 acceptance tests
  .github/workflows/acceptance_tests.yml
Labels: skip-changelog

#22 Unit tests: Update Runner Windows 2019->2025
  .github/workflows/unit_tests.yaml
Labels: skip-changelog

#19 Detect Windows Server 2025
  lib/facter/util/facts/windows_release_finder.rb
  spec/facter/util/facts/windows_release_finder_spec.rb
Labels: enhancement

#17 Match class & file name for Solaris Filesystems
  lib/facter/facts/solaris/filesystems.rb
  lib/facter/resolvers/solaris/filesystems.rb
  spec/facter/facts/solaris/filesystems_spec.rb
  spec/facter/resolvers/solaris/filesystems_spec.rb
Labels: backwards-incompatible

#13 Add support for ZFS facts on GNU/Linux
  lib/facter/facts/linux/zfs_featurenumbers.rb
  lib/facter/facts/linux/zfs_version.rb
  lib/facter/facts/linux/zpool_featureflags.rb
  lib/facter/facts/linux/zpool_featurenumbers.rb
  lib/facter/facts/linux/zpool_version.rb
  lib/facter/framework/core/file_loader.rb
  spec/facter/facts/linux/zfs_featurenumbers_spec.rb
  spec/facter/facts/linux/zfs_version_spec.rb
  spec/facter/facts/linux/zpool_featureflags_spec.rb
  spec/facter/facts/linux/zpool_featurenumbers_spec.rb
  spec/facter/facts/linux/zpool_version_spec.rb
Labels: enhancement

#26 Unit tests: Add Ruby 3.3 to matrix
  .github/workflows/unit_tests.yaml
Labels: enhancement

#16 Fix resolution of the `virtual` fact on FreeBSD
  lib/facter/util/facts/posix/virtual_detector.rb
Labels: bug

#28 Fix the release action
  tasks/vox.rake
Labels: skip-changelog

#29 CI: Fix Release workflow
  .github/workflows/gem_release.yaml
Labels: bug
